name: gosh_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.0
  share_plus: ^7.2.1
  flutter_html: ^3.0.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/default_avatar.png
    - assets/cover_placeholder.png
    - assets/user.png

    - assets/videos/video1.mp4
    - assets/videos/video2.mp4
    - assets/videos/video3.mp4

    - assets/icons/whatsapp.png
    - assets/icons/snapchat.png
    - assets/icons/instagram.png
    - assets/icons/facebook.png
    - assets/vip_wolf.png

    - assets/live_videos/live1.mp4
    - assets/live_videos/live2.mp4
    - assets/live_videos/live3.mp4
    - assets/live_videos/live4.mp4
    - assets/live_videos/live5.mp4
    - assets/live_videos/live6.mp4
    - assets/live_videos/live7.mp4
    - assets/live_videos/live8.mp4

    - assets/live_thumbnails/thumb1.jpg
    - assets/live_thumbnails/thumb2.jpg
    - assets/live_thumbnails/thumb3.jpg
    - assets/live_thumbnails/thumb4.jpg
    - assets/live_thumbnails/thumb5.jpg
    - assets/live_thumbnails/thumb6.jpg
    - assets/live_thumbnails/thumb7.jpg
    - assets/live_thumbnails/thumb8.jpg
